name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - master
    - next
    - renovate/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai

    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
        restore-keys: |
          cypress-${{ runner.os }}-cypress-

    - run: yarn install --frozen-lockfile
      env:
        CYPRESS_INSTALL_BINARY: ''
        CYPRESS_DOWNLOAD_MIRROR: ''

    - run: yarn build

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: yarn test:ci

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./.coverage/lcov.info

  e2e-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: yarn test:e2e:ci
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  publish:
    needs: [build, unit-test, e2e-test]
    runs-on: ubuntu-latest
    steps:
    - uses: easyops-cn/actions-next-publish-from-tags@master
      with:
        npm-token: ${{ secrets.NPM_TOKEN }}
      if: github.event_name == 'push'
